
default: &default
  adapter: postgresql
  encoding: unicode
  pool: 5

development:
  <<: *default
  database: utcoverseas_development
  username: eperez
  password:
  host: localhost
  port: 5432  kk


test:
  <<: *default
  database: utcoverseas_test


production:
  <<: *default
  url: <%= ENV["DATABASE_URL"] %>
  pool: <%= ENV["DB_POOL"] || ENV['MAX_THREADS'] || 5 %>
